window.ENTRY = {
  "category": "classes",
  "id": "the-tailor",
  "name": "The Tailor <span style=\"color: var(--ink-dim); font-weight: 400;\">→ The Weaver</span>",
  "eyebrow": "Class Sheet — Full 1–99 Progression",
  "subtitle": "Controller / Binder / Battlefield Manipulator",
  "faction": null,
  "tags": [
    "<span class=\"tag\">Founding Concept — fully built out</span>"
  ],
  "bodyHtml": `
<img class="portrait-img" src="images/the-tailor.png" alt="The Tailor → The Weaver" onerror="this.outerHTML='&lt;div class=&quot;portrait-slot&quot;&gt;Character portrait — pending&lt;span class=&quot;sub&quot;&gt;art prompt not yet generated&lt;/span&gt;&lt;/div&gt;'">
<div class="quote-block">"Everything down here is torn. I just happen to carry the needle."</div>
<h2>Overview</h2>
<p><strong>Core Resource:</strong> Thread — stacks generated by landing binds, tethers, and stitched effects on enemies; spent on the class's signature weaving abilities. Decays slowly if unused, rewarding a controller who keeps applying binds over one who hoards.</p>
<p><strong>Evolution:</strong> At Level 50, becomes <strong>The Weaver</strong>.</p>
<p><strong>Primary Attribute:</strong> PRESENCE (bind/debuff potency)  ·  <strong>Secondary Attribute:</strong> REFLEX (needle-speed, turn order, precision strikes)</p>
<h2>Skill Efficiency</h2>
<table class="rel-table">
<tr><th>Weight</th><th>Skills</th></tr>
<tr><td>Major (1.0x)</td><td>Textiles (Tailoring/Binding/Nets), Blade-work (needles, shears)</td></tr>
<tr><td>Minor (0.5x)</td><td>Persuasion, Composure</td></tr>
<tr><td>Misc (0.2x)</td><td>Scavenging, Mechanics</td></tr>
</table>
<h2>Tier 1 — The Seamstress (Levels 1–20)</h2>
<p class="flavor">Tagging enemies, learning the bind, building Thread.</p>
<table class="rel-table">
<tr><th>Lvl</th><th>Ability</th><th>Effect</th></tr>
<tr><td>1</td><td>Pin Prick <em>(Active)</em></td><td>Light damage, generates 1 Thread. Damage = Blade-work × 1.5.</td></tr>
<tr><td>5</td><td>Measure Twice <em>(Passive)</em></td><td>First attack each combat gains +15% Accuracy.</td></tr>
<tr><td>10</td><td>Baste Stitch <em>(Active)</em></td><td>Tethers two enemies for 2 turns; 25%+ of damage dealt to one mirrors to the other.</td></tr>
<tr><td>15</td><td>Bobbin Toss <em>(Active)</em></td><td>Light damage + Slow (2 turns), generates 1 Thread on hit.</td></tr>
<tr><td>20</td><td>CROSS-STITCH <em>(Ultimate)</em></td><td>Locks all Front Row enemies' row position for 2 turns; damage per target scales with Thread spent. Consumes all Thread.</td></tr>
</table>
<h2>Tier 2 — The Draper (Levels 21–49)</h2>
<p class="flavor">Thread economy, field control, first cuts of real menace.</p>
<table class="rel-table">
<tr><th>Lvl</th><th>Ability</th><th>Effect</th></tr>
<tr><td>25</td><td>Loose Ends <em>(Active)</em></td><td>Detonates all current Thread for AoE damage to bound/tethered enemies. Consumes all Thread.</td></tr>
<tr><td>30</td><td>Bolt of Cloth <em>(Passive)</em></td><td>Max Thread capacity increases to 10; Thread no longer decays between turns.</td></tr>
<tr><td>35</td><td>Suture <em>(Active)</em></td><td>Heals self or an ally. Consumes 2 Thread.</td></tr>
<tr><td>42</td><td>Garrote Thread <em>(Active)</em></td><td>Single-target attack, applies Bleed and a chance to Stun. Consumes 1 Thread.</td></tr>
<tr><td>48</td><td>Pattern Recognition <em>(Passive)</em></td><td>Thread generation doubled when landing a bind on an already-Exposed target.</td></tr>
</table>
<h2>⚡ Evolution Event — Level 50</h2>
<table class="rel-table">
<tr><th>Requirement</th><td>Textiles Lvl 40+</td></tr>
<tr><th>Cost</th><td>10 Neon Glass + 1 Spool of Mono-Filament Wire</td></tr>
<tr><th>Location</th><td>The Loom</td></tr>
<tr><th>Visual Shift</th><td>The sewing kit is gone. Mono-filament wire spools directly from housings grafted into both forearms, fingers tipped with thread-guides instead of nails. A faint, near-invisible web trails from their hands whenever they move — you don't see it until it's already around something.</td></tr>
</table>
<p style="text-align:center; font-family: var(--font-display); text-transform: uppercase; letter-spacing: 0.05em; color: var(--neon-primary); margin: 16px 0;">Name Change → The Weaver</p>
<h2>Tier 3 — The Loom-Bound (Levels 50–75)</h2>
<p class="flavor">The wire ignores range, ignores rows, ignores the rules a needle couldn't.</p>
<table class="rel-table">
<tr><th>Lvl</th><th>Ability</th><th>Effect</th></tr>
<tr><td>51</td><td>Filament Lash <em>(Active)</em></td><td>Single-target strike that ignores Front/Back Row targeting restrictions.</td></tr>
<tr><td>55</td><td>Web Sense <em>(Passive)</em></td><td>+5% Dodge Chance per bound/tethered enemy (max +20%).</td></tr>
<tr><td>60</td><td>Cat's Cradle <em>(Active)</em></td><td>Binds up to 3 enemies in a shared web for 3 turns; damage dealt to any mirrors to the others at reduced value. Costs 2 Thread.</td></tr>
<tr><td>65</td><td>Unravel <em>(Active)</em></td><td>Strips a positive status from a target; the stripped effect converts into 2 Thread.</td></tr>
<tr><td>70</td><td>Reinforced Weave <em>(Passive)</em></td><td>Allies benefiting from a Weaver bind gain +15% Damage Reduction.</td></tr>
<tr><td>75</td><td>THE FULL BOLT <em>(Ultimate)</em></td><td>Binds all enemies on the battlefield into a shared web for 3 turns — damage mirrors to all others at full value. Consumes all Thread.</td></tr>
</table>
<h2>Tier 4 — The Spinneret (Levels 76–99)</h2>
<p class="flavor">The Weaver stops binding the battlefield and starts authoring it.</p>
<table class="rel-table">
<tr><th>Lvl</th><th>Ability</th><th>Effect</th></tr>
<tr><td>80</td><td>Silk Armor <em>(Passive)</em></td><td>Allies affected by a Weaver bind gain a damage shield equal to the Thread spent to create it.</td></tr>
<tr><td>85</td><td>Puppet Strings <em>(Active)</em></td><td>Seizes control of one bound enemy's next action, forcing it to attack an ally of the Weaver's choosing. Costs 4 Thread.</td></tr>
<tr><td>90</td><td>Infinite Spool <em>(Passive)</em></td><td>Removes the Thread cap entirely; all Thread generation doubled.</td></tr>
<tr><td>95</td><td>Severance <em>(Active)</em></td><td>Instantly executes any bound enemy below 25% HP; deals heavy damage otherwise. Costs 6 Thread.</td></tr>
<tr><td>99</td><td>THE LAST STITCH <em>(Final)</em></td><td>Fully heals all allies and simultaneously binds all enemies into a shared web that takes damage equal to the total amount healed this turn.</td></tr>
</table>
<div class="quote-block">"I told you. I sew the world back together, one thread at a time — I never said which side of the needle you'd end up on."</div>
<h2>Why This Progression Works</h2>
<p><strong>The Textiles Synergy:</strong> Nearly every capstone ability — Loose Ends, Cross-Stitch, The Full Bolt — is a Thread-dump, not a raw damage scaler. A Weaver who never bothers to apply their binds simply won't have the Thread to make their big moments hit hard. The class rewards constant, active control over passive stat-stacking.</p>
<p><strong>The Bind-or-Bust Gate:</strong> Web Sense, Reinforced Weave, and Silk Armor all key off <em>currently active binds</em>, not the Weaver's own stats. A Weaver who lets their tethers lapse loses their dodge bonus, their allies lose their damage reduction, and their shields stop generating.</p>
<p><strong>The Fantasy Arc:</strong> Level 1 — a garment worker with a sidearm sewing kit, throwing bobbins and hoping the thread holds. Level 50 — a battlefield controller wired with mono-filament, binding entire fronts of enemies together. Level 99 — something closer to fate itself, healer and executioner running through the exact same thread, at the exact same moment.</p>
`,
  "footer": [
    "Source: class_the_tailor.md",
    "Founding concept from World Bible, fully built out"
  ]
};
