-- Migration 005: Skill system on world_config
--
-- Adds skill_system_json, generated by the Skills section of the Stat
-- Labels wizard step (Step 5). Two parts, generated once per world and
-- referenced consistently afterward instead of being invented ad hoc on
-- every class/item generation call:
--   - weaponSkills: world-flavored display names for the 7 mechanically
--     fixed weapon categories (canonical keys/numeric balance ranges
--     never change -- see lib/itemFormulas.js -- only the label shown to
--     a reader does).
--   - fieldSkills: a fixed pool of invented flavor skills (e.g.
--     "Grid-Tap," "Scavenging") that every class/item generation call
--     now draws from instead of inventing new ones each time, closing a
--     consistency gap where a large roster could accumulate several
--     near-duplicate skill names meaning the same thing.
--
-- Run this in the Supabase SQL editor. Idempotent-safe.

ALTER TABLE world_config
  ADD COLUMN IF NOT EXISTS skill_system_json jsonb;
